# Generated by Django 5.1.2 on 2024-10-16 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_description_document_title_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Document',
            new_name='File',
        ),
        migrations.RenameField(
            model_name='file',
            old_name='document',
            new_name='file',
        ),
    ]
